# -*- coding: utf-8 -*-
"""Banking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WObMlfeL2_z4M3ns0aydN8jr7I1Odlv
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbs
import numpy as np

df=pd.read_csv('/content/Banking.csv')
df.head()

df.describe()

df['Estimated Income'].min()

bins=[0,50000,100000,300000,float('inf')]
labels=['Lowest','Medium','High','Highest']
df['Income']=pd.cut(df['Estimated Income'],bins=bins,labels=labels)
df.head()
df['Income'].value_counts().plot(kind='bar')

categories=df[["BRId","GenderId","IAId","Amount of Credit Cards","Loyalty Classification","Occupation","Nationality","Properties Owned","Income"]]
for col in categories:
  print(f"value counts for'(col)':")
  display(df[col].value_counts())

"""Univariete Analysis: Analysis on All Columns"""

for i, predictor in enumerate(df[["BRId","GenderId","IAId","Amount of Credit Cards","Loyalty Classification","Occupation","Nationality","Properties Owned","Income"]]):
    plt.figure(i)
    sbs.countplot(data=df, x=predictor)

"""Bivariate Analysis: Analysis on Specific Columns to get data more in detail in visual charts"""

for i, predictor in enumerate(df[["BRId","GenderId","IAId","Amount of Credit Cards","Loyalty Classification","Occupation","Nationality","Properties Owned","Income"]]):
    plt.figure(i)
    sbs.countplot(data=df, x=predictor, hue='GenderId')

numerical=['Estimated Income','Bank Deposits','Bank Loans','Credit Card Balance','Superannuation Savings','Checking Accounts']
plt.figure(figsize=(9,36))
for i, col in enumerate(numerical):
  plt.subplot(6,2,i+1)
  sbs.histplot(df[col],kde=True)
  plt.title(col)
plt.show()

"""Heatmaps"""

numerical=['Estimated Income','Bank Deposits','Bank Loans','Credit Card Balance','Superannuation Savings','Checking Accounts']
heatmap=df[numerical].corr()
plt.figure(figsize=(12,12))
sbs.heatmap(heatmap,annot=True,cmap='PiYG')